"""Replace Enum with String and CHECK constraint for User.role

Revision ID: 37fe093d1555
Revises: 98e0912df562
Create Date: 2024-11-28 13:47:50.556559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37fe093d1555'
down_revision: Union[str, None] = '98e0912df562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'EDITOR', 'VIEWER', name='userrole'),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('ADMIN', 'EDITOR', 'VIEWER', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###
